name: Test and Package bank_lib

on:
  push:
    branches: [master]
    tags: ['*', 'v**']
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Build & Test
        run: |
          cmake -H. -B_build
          cmake --build _build
          cmake --build _build --target test -- ARGS=--verbose

      - name: Report to Coveralls
        uses: threeal/gcovr-action@v1.0.0
        with:
          excludes: third-party
          coveralls-send: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Solver
        run: cmake ${{ github.workspace }} -B ${{ github.workspace }}/build -D PRINT_VERSION=${GITHUB_REF_NAME#v}

      - name: Build Solver
        run: cmake --build ${{ github.workspace }}/build

      - name: Build package
        run: cmake --build ${{ github.workspace }}/build --target package

      - name: Build source package
        run: cmake --build ${{ github.workspace }}/build --target package_source

      - name: Make a release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "build/*.deb,build/*.tar.gz,build/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          allowUpdates: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: example
          path: build/solver
