name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  tags:
    - 'v*.*.*.*'

jobs:
  build_Linux:
    runs-on: ubuntu-latest
    env:
      REF: ${{ github.ref }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure Project
        run: cmake ${{ github.workspace }} -B ${{ github.workspace }}/build -D PRINT_VERSION=${{ github.ref_name#v }}

      - name: Build Project
        run: cmake --build ${{ github.workspace }}/build

      - name: Build tar.gz
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd ${{ github.workspace }}/build
          cpack -G "TGZ"
          mv *.tar.gz ${{ github.workspace }}/artifacts
          tree ${{ github.workspace }}/artifacts

      - name: Build deb
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd ${{ github.workspace }}/build
          cpack -G DEB
          mv *.deb ${{ github.workspace }}/artifacts
          tree ${{ github.workspace }}/artifacts

      - name: Build rpm
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd ${{ github.workspace }}/build
          cpack -G RPM
          mv *.rpm ${{ github.workspace }}/artifacts
          tree ${{ github.workspace }}/artifacts

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ${{ github.workspace }}/artifacts

  build_macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure Project
        run: cmake ${{ github.workspace }} -B ${{ github.workspace }}/build -D PRINT_VERSION=${{ github.ref_name#v }}

      - name: Build Project
        run: cmake --build ${{ github.workspace }}/build

      - name: Build dmg
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd ${{ github.workspace }}/build
          cpack -G DragNDrop
          mv *.dmg ${{ github.workspace }}/artifacts
          tree ${{ github.workspace }}/artifacts

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ${{ github.workspace }}/artifacts

  build_Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure Project
        run: cmake ${{ github.workspace }} -B ${{ github.workspace }}/build -D PRINT_VERSION=${{ github.ref_name#v }}

      - name: Build Project
        run: cmake --build ${{ github.workspace }}/build

      - name: Build msi
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd ${{ github.workspace }}/build
          cpack -G WIX
          mv *.msi ${{ github.workspace }}/artifacts
          tree ${{ github.workspace }}/artifacts

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ${{ github.workspace }}/artifacts
